DROP TABLE IF EXIST users;
DROP TABLE IF EXIST shops;
DROP TABLE IF EXIST inventories;
DROP TABLE IF EXIST sales;
DROP TABLE IF EXIST expenses;
DROP TABLE IF EXIST payouts;
DROP TABLE IF EXIST banks;
DROP TABLE IF EXIST tokens;