// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: expense.sql

package db

import (
	"context"
	"time"
)

const createExpenses = `-- name: CreateExpenses :one
INSERT INTO expenses (
  particular,
  amount,
  recipient,
  payment_type,
  shop_id
) VALUES (
  $1, $2, $3,$4, $5
)
RETURNING id, particular, amount, recipient, payment_type, shop_id, created_at
`

type CreateExpensesParams struct {
	Particular  string `json:"particular"`
	Amount      int32  `json:"amount"`
	Recipient   string `json:"recipient"`
	PaymentType string `json:"payment_type"`
	ShopID      int32  `json:"shop_id"`
}

func (q *Queries) CreateExpenses(ctx context.Context, arg CreateExpensesParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, createExpenses,
		arg.Particular,
		arg.Amount,
		arg.Recipient,
		arg.PaymentType,
		arg.ShopID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Particular,
		&i.Amount,
		&i.Recipient,
		&i.PaymentType,
		&i.ShopID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :exec
DELETE FROM expenses
WHERE id = $1
`

func (q *Queries) DeleteExpense(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteExpense, id)
	return err
}

const getExpenseById = `-- name: GetExpenseById :one
SELECT id, particular, amount, recipient, payment_type, shop_id, created_at FROM expenses
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetExpenseById(ctx context.Context, id int32) (Expense, error) {
	row := q.db.QueryRowContext(ctx, getExpenseById, id)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Particular,
		&i.Amount,
		&i.Recipient,
		&i.PaymentType,
		&i.ShopID,
		&i.CreatedAt,
	)
	return i, err
}

const listMyExpenses = `-- name: ListMyExpenses :many
SELECT id, particular, amount, recipient, payment_type, shop_id, created_at FROM expenses
WHERE shop_id = $1
ORDER BY id 
LIMIT $2
OFFSET $3
`

type ListMyExpensesParams struct {
	ShopID int32 `json:"shop_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListMyExpenses(ctx context.Context, arg ListMyExpensesParams) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, listMyExpenses, arg.ShopID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Expense{}
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.Particular,
			&i.Amount,
			&i.Recipient,
			&i.PaymentType,
			&i.ShopID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchExpensesBetweenDates = `-- name: SearchExpensesBetweenDates :many
SELECT id, particular, amount, recipient, payment_type, shop_id, created_at FROM expenses
WHERE shop_id = $1 AND created_at BETWEEN $2 AND $3
ORDER BY id 
LIMIT $4
OFFSET $5
`

type SearchExpensesBetweenDatesParams struct {
	ShopID      int32     `json:"shop_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) SearchExpensesBetweenDates(ctx context.Context, arg SearchExpensesBetweenDatesParams) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, searchExpensesBetweenDates,
		arg.ShopID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Expense{}
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.Particular,
			&i.Amount,
			&i.Recipient,
			&i.PaymentType,
			&i.ShopID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
