// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"time"
)

type Bank struct {
	ID            int32     `json:"id"`
	BankName      string    `json:"bank_name"`
	Icon          string    `json:"icon"`
	AccountNumber string    `json:"account_number"`
	ShopID        int32     `json:"shop_id"`
	CreatedAt     time.Time `json:"created_at"`
}

type Expense struct {
	ID          int32     `json:"id"`
	Particular  string    `json:"particular"`
	Amount      int32     `json:"amount"`
	Recipient   string    `json:"recipient"`
	PaymentType string    `json:"payment_type"`
	ShopID      int32     `json:"shop_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type Inventory struct {
	ID                   int32     `json:"id"`
	ItemName             string    `json:"item_name"`
	Quantity             int32     `json:"quantity"`
	CostPrice            int32     `json:"cost_price"`
	SellingPriceStandard int32     `json:"selling_price_standard"`
	Status               string    `json:"status"`
	ShopID               int32     `json:"shop_id"`
	CreatedAt            time.Time `json:"created_at"`
}

type Payout struct {
	ID          int32     `json:"id"`
	Particular  string    `json:"particular"`
	Amount      int32     `json:"amount"`
	Recipient   string    `json:"recipient"`
	PaymentType string    `json:"payment_type"`
	ShopID      int32     `json:"shop_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type Sale struct {
	ID                 int32     `json:"id"`
	ItemID             int32     `json:"item_id"`
	Quantity           int32     `json:"quantity"`
	SellingPriceActual int32     `json:"selling_price_actual"`
	PaymentType        string    `json:"payment_type"`
	ShopID             int32     `json:"shop_id"`
	CreatedAt          time.Time `json:"created_at"`
}

type Shop struct {
	ID        int32     `json:"id"`
	ShopName  string    `json:"shop_name"`
	ShopType  string    `json:"shop_type"`
	Address   string    `json:"address"`
	UserID    int32     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Token struct {
	ID           int32          `json:"id"`
	UserID       int32          `json:"user_id"`
	AccessToken  sql.NullString `json:"access_token"`
	RefreshToken sql.NullString `json:"refresh_token"`
}

type User struct {
	ID         int32     `json:"id"`
	FirstName  string    `json:"first_name"`
	LastName   string    `json:"last_name"`
	Email      string    `json:"email"`
	Password   string    `json:"password"`
	IsVerified bool      `json:"isVerified"`
	CreatedAt  time.Time `json:"created_at"`
}
